### PR TITLE
Add initial files + searchAPI implementation

### PR DESCRIPTION
**Pull request by Flanker-shyam**
I have created a new folder to start this project and Implemented searchAPI

### CODE REVIEW

**Comment by Flanker-shyam** [comment]
Fine !

**Comment by ravi-prakash-v** [comment]
Hi @Flanker-shyam this is a specification repository. I will create another repo and share, you can raise your PR in that.

**Comment by Flanker-shyam** [comment]
> Hi @Flanker-shyam this is a specification repository. I will create another repo and share, you can raise your PR in that.

Thanks @ravi-prakash-v , I will look into it.

**Comment by ravi-prakash-v** [comment]
Closing this PR as the specification has been updated since Sep 25. @Flanker-shyam please do follow the Issue board for further updates. Your contributions to this repo are greatly appreciated. Thank you for your valuable time. We will continue to reach out to you for more contributions. 

Closing this PR for now.

**Pull request closed without merging**
